

CREATE DATABASE LIBRARY;

USE LIBRARY; 


CREATE TABLE BOOKS(
Isbn BIGINT,
Title VARCHAR(210),
PRIMARY KEY(Isbn));


CREATE TABLE AUTHORS(
Author_id INT AUTO_INCREMENT,
Name VARCHAR(100),
PRIMARY KEY(Author_id));


CREATE TABLE BOOK_AUTHORS(
Author_id INT,
Isbn BIGINT,
PRIMARY KEY(Author_id,Isbn),
FOREIGN KEY(Author_id) REFERENCES AUTHORS(Author_id),
FOREIGN KEY(Isbn) REFERENCES BOOKS(Isbn));


CREATE TABLE BORROWER(
Card_id INT AUTO_INCREMENT,
Ssn CHAR(11) NOT NULL,
Bname VARCHAR(30) NOT NULL,
Address VARCHAR(200) NOT NULL,
Phone VARCHAR(30) NOT NULL,
PRIMARY KEY(Card_id),
UNIQUE(Ssn));


CREATE TABLE BOOK_LOANS(
Loan_id INT AUTO_INCREMENT,
Isbn BIGINT,
Card_id INT,
Date_out DATE,
Due_date DATE,
Date_in DATE,
PRIMARY KEY(Loan_id),
FOREIGN KEY(Isbn) REFERENCES BOOKS(Isbn),
FOREIGN KEY(Card_id) REFERENCES BORROWER(Card_id));


CREATE TABLE FINES(
Loan_id INT,
Fine_amt FLOAT DEFAULT 0,
Paid BOOLEAN DEFAULT False,
PRIMARY KEY(Loan_id),
FOREIGN KEY(Loan_id) REFERENCES BOOK_LOANS(Loan_id));


CREATE TABLE LIBRARIANS(
Empid INT,
Password VARCHAR(30),
UNIQUE(Empid),
UNIQUE(Password));


